apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mrdom-logs-pvc
  namespace: mrdom
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mrdom-data-pvc
  namespace: mrdom
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: gp2
